WITH CTE_CapacidadeVeiculos AS ( -- VALORES INFERIDOS PELA GERENCIA COMO PADRÃO ATÉ OCR VOLTAR A FUNCIONAR PARA CAPTURAR INFORMACOES DE PESO E PESO MAXIMO DO VEICULO
    SELECT 'CAMINHAO 3/4' AS T_VEICULO, 2 AS EIXOS, 6 AS PNEUS, 4000 AS PESO_MAX, 4200 AS PESO_TOLERANCIA
    UNION ALL SELECT 'CAMINHAO BITRUCK', 	4, 12, 22000, 23100
    UNION ALL SELECT 'CAMINHAO TOCO', 		2, 6, 6000, 6300
    UNION ALL SELECT 'CAMINHAO TRUCK', 		3, 10, 14000, 14700
    UNION ALL SELECT 'CARRETA', 			5, 16, 32000, 33600
    UNION ALL SELECT 'CAVALO', 				3, 10, NULL, NULL
    UNION ALL SELECT 'HR', 					2, 4, 1500, 1575
    UNION ALL SELECT 'MOTO', 				2, 2, 20, 21
    UNION ALL SELECT 'PASSAGEIRO', 			2, 4, 1200, 1260
    UNION ALL SELECT 'UTILITARIO', 			2, 4, 800, 840
    UNION ALL SELECT 'VAN', 				2, 4, 1500, 1575
    UNION ALL SELECT 'VAN RENTAL', 			2, 4, 1500, 1575
    UNION ALL SELECT 'VUC', 				2, 6, 3000, 3150
)
, BASE AS (
			SELECT
				  [VIAGEM] 						AS ID_VIAGEM
				, [NUMERO DE CONTROLE] 			AS ID_CONTROLE
				, CAST([DATA INICIO] AS DATE)	AS DT_INICIO_VIAGEM
				, [COOPERADO]
				, [CLIENTE]
				, [FILIAL]
				, [FILIAL FISCAL]				AS FILIAL_FISCAL
				, [ORIGEM]
				, [DESTINO]
				, [VEICULO]
				, [TIPO DE VEICULO]				AS TIPO_VEICULO
				, [PESO]
				, PESO_MAX
				, PESO_TOLERANCIA
				, CASE
					WHEN ([PESO] - PESO_MAX) < 0 
					THEN 0 
					ELSE ([PESO] - PESO_MAX)
				END 							AS PESO_EXCEDENTE
				, EIXOS
				, PNEUS
				, [VALOR DO FRETE DA VIAGEM]	AS VL_FRETE
				, [VALOR DA MERCADORIA]			AS VL_MERCADORIA
				, [CENTRO CUSTO]				AS CENTRO_CUSTO
				, [UNIDADE DE NEGOCIO]			AS UNIDADE_NEGOCIO
			FROM SCHEMA_.VIEW_VIAGEM
			LEFT JOIN CTE_CapacidadeVeiculos ON CTE_CapacidadeVeiculos.T_VEICULO = VIEW_VIAGEM.[TIPO DE VEICULO]
			WHERE (CAST([DATA INICIO] AS DATE) > = DATEADD(YEAR, -1, GETDATE())
					AND CAST([DATA INICIO] AS DATE) <= CAST(GETDATE() AS DATE)))
SELECT
	ID_VIAGEM
	, ID_CONTROLE
	, DT_INICIO_VIAGEM
	, COOPERADO
	, CLIENTE
	, FILIAL
	, FILIAL_FISCAL
	, ORIGEM
	, DESTINO
	, VEICULO
	, TIPO_VEICULO
	, PESO
	, PESO_MAX
	, PESO_EXCEDENTE
	, EIXOS
	, PNEUS
	, VL_FRETE
	, VL_MERCADORIA
	, CENTRO_CUSTO
	, UNIDADE_NEGOCIO
	, ROUND(PESO/PESO_MAX,2) AS INDICE_DESGASTE_PNEUS
	, CASE WHEN (PESO/PESO_MAX) > 1 THEN 1 ELSE 0 END PREVISAO_DESGASTE_PNEUS	
	, CASE
		WHEN ROUND(PESO/PESO_MAX,1) < 0.8					THEN 'BAIXO'
		WHEN ROUND(PESO/PESO_MAX,1) BETWEEN 0.8 AND 1.0 	THEN 'IDEAL'
		WHEN ROUND(PESO/PESO_MAX,1) BETWEEN 1.0 AND 1.2 	THEN 'ATENÇÃO'
		WHEN ROUND(PESO/PESO_MAX,1) > 1.2 					THEN 'CRITICO'
		WHEN ROUND(PESO/PESO_MAX,1) IS NULL					THEN 'N/A'
	END AS FAIXA_DESGASTE
	, CASE
		WHEN ROUND(PESO/PESO_MAX,1) < 0.8					THEN 1
		WHEN ROUND(PESO/PESO_MAX,1) BETWEEN 0.8 AND 1.0 	THEN 2
		WHEN ROUND(PESO/PESO_MAX,1) BETWEEN 1.0 AND 1.2 	THEN 3
		WHEN ROUND(PESO/PESO_MAX,1) > 1.2 					THEN 4
	END AS SCORE_DESGASTE
	, CASE
		WHEN ROUND(PESO/PESO_MAX,2) > 1.00 AND ROUND(PESO/PESO_MAX,2) <= 1.05
		THEN 1
		ELSE 0
	END VEICULO_COM_SOBRECARGA_TOLERAVEL
	, CASE 
		WHEN ROUND(PESO/PESO_MAX,2) <= 1.00 									THEN 'CONFERMIDADE'
		WHEN ROUND(PESO/PESO_MAX,2) > 1.00 AND ROUND(PESO/PESO_MAX,2) <= 1.05 	THEN 'TOLERÁVEL'
		WHEN ROUND(PESO/PESO_MAX,2) > 1.05 										THEN 'SOBRECARGA'
	END as STATUS_CARGA	
	, 	CASE
			WHEN PESO_EXCEDENTE > 0 	AND PESO_EXCEDENTE <= 600 	THEN (CEILING(PESO_EXCEDENTE / 200) * 5.32)
			WHEN PESO_EXCEDENTE > 600 	AND PESO_EXCEDENTE <= 800 	THEN (CEILING(PESO_EXCEDENTE / 200) * 10.54)
			WHEN PESO_EXCEDENTE > 800 	AND PESO_EXCEDENTE <= 1000 	THEN (CEILING(PESO_EXCEDENTE / 200) * 21.28)
			WHEN PESO_EXCEDENTE > 1000 	AND PESO_EXCEDENTE <= 3000 	THEN (CEILING(PESO_EXCEDENTE / 200) * 31.92)
			WHEN PESO_EXCEDENTE > 3000 	AND PESO_EXCEDENTE <= 5000 	THEN (CEILING(PESO_EXCEDENTE / 200) * 42.56)
			WHEN PESO_EXCEDENTE > 5000							 	THEN (CEILING(PESO_EXCEDENTE / 200) * 53.20)
		END AS MULTA_PREVISTA
FROM BASE